function T(id, fc, title, code, scenario, k, r, s, ratings) {
  const obj = { id, filterCode: fc, title, code, scenario, knowledge: k, risk: r, skill: s };
  if (ratings) obj.ratings = ratings;
  return obj;
}
function K(code, text) { return { code, text }; }
function R(code, text) { return { code, text }; }
function S(code, text) { return { code, text }; }

export const COMMERCIAL_DATA = [
{ id:"I", roman:"I", title:"Preflight Preparation", phase:"ground", tasks:[
T("A","I_A","Pilot Qualifications","CA.I.A",
"You're offered a job flying an aerial survey. Walk me through commercial pilot privileges, limitations, and the regulatory requirements.",
[K("K1","Commercial pilot certification requirements and recent experience (14 CFR 61)"),K("K2","Privileges and limitations of a commercial pilot (14 CFR 61.133)"),K("K3","Medical certificate requirements (First or Second class)"),K("K4","Operating limitations for commercial operations")],
[R("R1","Exceeding commercial pilot privileges"),R("R2","Operating without proper currency or ratings")],
[S("S1","Apply requirements to maintain and exercise commercial pilot privileges")]),
T("B","I_B","Airworthiness Requirements","CA.I.B",
"This aircraft is used for commercial operations. What additional airworthiness requirements apply beyond private operations?",
[K("K1","Airworthiness requirements for commercial operations (14 CFR 91 & 135)"),K("K2","100-hour inspection requirements"),K("K3","MEL and KOEL applicability"),K("K4","Required equipment for commercial operations")],
[R("R1","Operating with inadequate inspections"),R("R2","Inadequate MEL compliance")],
[S("S1","Determine airworthiness for commercial operations"),S("S2","Apply 100-hour and annual inspection requirements")]),
T("C","I_C","Weather Information","CA.I.C",
"You're planning a 300 NM commercial flight. Brief me on all weather products you'd review and your decision-making process.",
[K("K1","Weather data sources for commercial flight planning"),K("K2","Interpretation of aviation weather products"),K("K3","Convective weather analysis"),K("K4","Icing and turbulence forecasting")],
[R("R1","Pressing into deteriorating weather"),R("R2","Inadequate weather briefing for commercial operations")],
[S("S1","Obtain and analyze a complete weather briefing"),S("S2","Make a go/no-go decision based on weather analysis")]),
T("D","I_D","Cross-Country Flight Planning","CA.I.D",
"Plan a commercial cross-country flight. Demonstrate thorough flight planning including fuel management and alternates.",
[K("K1","Cross-country flight planning at the commercial level"),K("K2","Fuel requirements and reserves"),K("K3","Performance planning for various conditions")],
[R("R1","Inadequate fuel reserves"),R("R2","Failure to plan alternates")],
[S("S1","Prepare and present a complete cross-country plan"),S("S2","Calculate accurate fuel requirements with reserves")]),
T("E","I_E","National Airspace System","CA.I.E",
"Your commercial flight path crosses multiple airspace classes. Explain requirements and procedures for each.",
[K("K1","Airspace classes and requirements"),K("K2","Special use and other airspace"),K("K3","ATC clearances and procedures for complex airspace")],
[R("R1","Airspace violations"),R("R2","Failure to comply with ATC clearances")],
[S("S1","Navigate through complex airspace environments"),S("S2","Comply with all airspace requirements")]),
T("F","I_F","Performance and Limitations","CA.I.F",
"Calculate performance for a hot day, maximum gross weight departure from a short runway. Is this flight safe?",
[K("K1","Advanced performance calculations"),K("K2","Density altitude effects on commercial operations"),K("K3","Weight and balance for maximum gross weight operations"),K("K4","Accelerate-stop and accelerate-go distances")],
[R("R1","Operating at performance limits"),R("R2","Insufficient performance margins")],
[S("S1","Perform comprehensive performance calculations"),S("S2","Determine adequate safety margins")]),
T("G","I_G","Operation of Systems","CA.I.G",
"Describe the operation of all aircraft systems in detail, including emergency procedures for each system failure.",
[K("K1","Detailed aircraft systems knowledge"),K("K2","Complex aircraft systems (retractable gear, constant-speed prop)"),K("K3","Emergency procedures for system failures")],
[R("R1","Inadequate systems knowledge"),R("R2","Improper emergency procedures")],
[S("S1","Demonstrate thorough knowledge of all aircraft systems"),S("S2","Describe emergency procedures for system failures")]),
T("H","I_H","Human Factors","CA.I.H",
"As a commercial pilot, what additional human factors considerations apply? Discuss CRM, fatigue management, and ADM.",
[K("K1","Advanced ADM for commercial operations"),K("K2","CRM principles and application"),K("K3","Fatigue risk management"),K("K4","Hazardous attitudes and commercial pressures")],
[R("R1","Commercial pressure to fly in unsafe conditions"),R("R2","Fatigue from demanding schedules")],
[S("S1","Apply advanced ADM and CRM principles"),S("S2","Develop effective fatigue mitigation strategies")])
]},
{ id:"II", roman:"II", title:"Preflight Procedures", phase:"ground", tasks:[
T("A","II_A","Preflight Assessment","CA.II.A",
"Conduct a thorough preflight inspection appropriate for commercial operations.",
[K("K1","Commercial-level preflight inspection standards"),K("K2","Complex aircraft preflight requirements")],
[R("R1","Inadequate preflight for commercial operations"),R("R2","Missing critical items on complex aircraft")],
[S("S1","Perform thorough preflight inspection"),S("S2","Verify all commercial airworthiness requirements")]),
T("B","II_B","Flight Deck Management","CA.II.B",
"Demonstrate professional flight deck management including passenger/payload management.",
[K("K1","Professional flight deck organization"),K("K2","Sterile cockpit concept"),K("K3","Crew coordination procedures")],
[R("R1","Inadequate flight deck preparation"),R("R2","Failure to maintain sterile cockpit")],
[S("S1","Organize the flight deck professionally"),S("S2","Conduct comprehensive passenger/crew briefing")]),
T("C","II_C","Engine Starting","CA.II.C",
"Demonstrate proper engine start procedures for a complex aircraft.",
[K("K1","Complex aircraft engine start procedures"),K("K2","External power and GPU operations")],
[R("R1","Improper start procedures for complex aircraft"),R("R2","Hot start or hung start conditions")],
[S("S1","Complete engine start per POH"),S("S2","Monitor all engine parameters during start")]),
T("D","II_D","Taxiing","CA.II.D",
"Taxi at a controlled airport, demonstrating professional communication and situational awareness.",
[K("K1","Complex airport taxi procedures"),K("K2","Hot spot awareness and runway safety"),K("K3","Retractable gear and complex aircraft taxi considerations")],
[R("R1","Runway incursion at complex airports"),R("R2","Improper taxi procedures with complex aircraft")],
[S("S1","Navigate complex airport surfaces safely"),S("S2","Maintain professional ATC communications")]),
T("F","II_F","Before Takeoff Check","CA.II.F",
"Perform the before-takeoff check for a complex aircraft including prop and system checks.",
[K("K1","Complex aircraft before-takeoff procedures"),K("K2","Propeller and constant-speed prop checks"),K("K3","Retractable gear system checks")],
[R("R1","Incomplete runup on complex aircraft"),R("R2","Missing critical system checks")],
[S("S1","Complete before-takeoff checklist for complex aircraft"),S("S2","Verify all systems operating within limits")])
]},
{ id:"III", roman:"III", title:"Airport and Seaplane Base Operations", phase:"flight", tasks:[
T("A","III_A","Communications, Light Signals, and Radar Services","CA.III.A",
"Demonstrate professional communication at both towered and non-towered airports.",
[K("K1","Professional ATC communication standards"),K("K2","Light gun signals and lost comm procedures"),K("K3","Radar services for commercial operations")],
[R("R1","Communication errors at busy airports"),R("R2","Loss of communication during commercial operations")],
[S("S1","Communicate professionally with ATC"),S("S2","Apply lost communication procedures")]),
T("B","III_B","Traffic Patterns","CA.III.B",
"Execute traffic pattern operations at various airport types demonstrating commercial-level precision.",
[K("K1","Traffic pattern procedures for various airport configurations"),K("K2","Wake turbulence avoidance in patterns")],
[R("R1","Traffic conflicts in busy patterns"),R("R2","Wake turbulence encounters")],
[S("S1","Fly precise traffic pattern procedures"),S("S2","Maintain commercial-level situational awareness")])
]},
{ id:"IV", roman:"IV", title:"Takeoffs, Landings, and Go-Arounds", phase:"flight", tasks:[
T("A","IV_A","Normal Takeoff and Climb","CA.IV.A",
"Demonstrate a normal takeoff with commercial-level precision in a complex aircraft.",
[K("K1","Normal takeoff procedures in complex aircraft"),K("K2","Prop, mixture, and power management during takeoff")],
[R("R1","Improper power management during takeoff"),R("R2","Failure to verify gear retraction")],
[S("S1","Execute takeoff with commercial precision"),S("S2","Manage complex aircraft systems during climb")]),
T("B","IV_B","Normal Approach and Landing","CA.IV.B",
"Execute a normal approach and landing demonstrating commercial-level precision.",
[K("K1","Stabilized approach criteria for commercial operations"),K("K2","Complex aircraft approach configuration")],
[R("R1","Unstabilized approach continued to landing"),R("R2","Gear-up landing risk")],
[S("S1","Fly a stabilized approach with commercial precision"),S("S2","Complete landing checklist including gear verification")]),
T("C","IV_C","Soft-Field Takeoff and Climb","CA.IV.C",
"Demonstrate soft-field takeoff technique in a complex aircraft.",
[K("K1","Soft-field procedures for complex aircraft"),K("K2","Prop and flap management for soft-field")],
[R("R1","Gear or surface damage from improper technique"),R("R2","Configuration errors during soft-field departure")],
[S("S1","Execute soft-field takeoff with proper technique"),S("S2","Manage complex systems during soft-field operations")],
["ASEL"]),
T("D","IV_D","Soft-Field Approach and Landing","CA.IV.D",
"Demonstrate a soft-field approach and landing in a complex aircraft.",
[K("K1","Soft-field landing technique for complex aircraft"),K("K2","Power management during soft-field landing")],
[R("R1","Hard landing on soft surface with complex aircraft"),R("R2","Gear damage from improper technique")],
[S("S1","Execute soft-field landing with minimum descent rate"),S("S2","Maintain proper configuration throughout")],
["ASEL"]),
T("E","IV_E","Short-Field Takeoff and Maximum Performance Climb","CA.IV.E",
"Demonstrate maximum performance takeoff from a short runway with obstacles.",
[K("K1","Maximum performance takeoff procedures"),K("K2","Accelerate-stop distance considerations")],
[R("R1","Inadequate performance margin for conditions"),R("R2","Configuration errors during short-field departure")],
[S("S1","Position at beginning of available runway"),S("S2","Achieve maximum performance climb"),S("S3","Clear obstacles at Vx, transition to Vy")],
["ASEL"]),
T("F","IV_F","Short-Field Approach and Landing","CA.IV.F",
"Demonstrate a precision short-field approach and landing within 100 feet of specified point.",
[K("K1","Precision approach to specified touchdown point"),K("K2","Energy management for short-field operations")],
[R("R1","Landing beyond specified zone"),R("R2","Inadequate stopping distance")],
[S("S1","Fly precision approach to touchdown point"),S("S2","Touch down within 100 feet of specified point"),S("S3","Apply maximum braking as required")],
["ASEL"]),
T("F2","IV_G","Power-Off 180 degrees  Accuracy Approach and Landing","CA.IV.G",
"From a normal traffic pattern altitude abeam the touchdown point, execute a power-off 180 degrees  glide approach and land within 200 feet of a designated line.",
[K("K1","Power-off 180 degrees  accuracy approach technique"),K("K2","Energy management during glide approach"),K("K3","Wind effect on glide path and base turn point")],
[R("R1","Misjudging glide distance"),R("R2","Excessive speed or altitude on final")],
[S("S1","Configure and establish glide from abeam point"),S("S2","Manage energy to reach touchdown zone"),S("S3","Touch down within 200 feet of designated line")],
["ASEL"]),
T("G","IV_H","Go-Around/Rejected Landing","CA.IV.H",
"Execute a go-around from various configurations demonstrating positive aircraft control.",
[K("K1","Go-around procedures for complex aircraft"),K("K2","Configuration management during go-around")],
[R("R1","Delayed go-around decision"),R("R2","Configuration errors during go-around")],
[S("S1","Execute timely go-around decision"),S("S2","Manage configuration changes smoothly"),S("S3","Establish positive climb at Vy")]),
T("H","IV_I","Forward Slip to a Landing","CA.IV.I",
"Demonstrate a forward slip to manage altitude on approach.",
[K("K1","Forward slip technique and limitations"),K("K2","POH restrictions on slips with flaps")],
[R("R1","Excessive sink rate during slip"),R("R2","Improper recovery from slip")],
[S("S1","Establish forward slip at appropriate point"),S("S2","Recover and land normally")],
["ASEL","ASES"]),
T("I","IV_J","Glassy Water Takeoff and Climb","CA.IV.J",
"The lake is perfectly calm. Demonstrate a glassy water takeoff with commercial-level precision.",
[K("K1","Glassy water takeoff procedures and hazards"),K("K2","Step taxi technique on glassy water"),K("K3","Visual reference challenges on glassy water")],
[R("R1","Inability to break free from water suction on glassy surface"),R("R2","Misjudging takeoff distance")],
[S("S1","Apply proper back pressure to get on the step"),S("S2","Maintain proper pitch to reduce water drag"),S("S3","Lift off and establish climb at Vy")],
["ASES","AMES"]),
T("J","IV_K","Glassy Water Approach and Landing","CA.IV.K",
"Demonstrate a glassy water landing. How do you establish a descent rate without visual cues from the water surface?",
[K("K1","Glassy water landing technique and hazards"),K("K2","Establishing a stabilized descent without visual surface cues"),K("K3","Use of power to control descent rate")],
[R("R1","Striking the water at excessive descent rate"),R("R2","Loss of depth perception on glassy water")],
[S("S1","Set up power-on approach at proper airspeed"),S("S2","Establish and maintain constant descent rate"),S("S3","Hold attitude until water contact, then reduce power")],
["ASES","AMES"]),
T("K","IV_L","Rough Water Takeoff and Climb","CA.IV.L",
"The water is choppy with whitecaps. Demonstrate a rough water takeoff technique at commercial standard.",
[K("K1","Rough water takeoff procedures"),K("K2","Use of flaps and power to minimize water impact"),K("K3","Porpoising recognition and correction")],
[R("R1","Structural damage from wave impact during takeoff"),R("R2","Porpoising leading to loss of control")],
[S("S1","Apply appropriate flaps and back pressure"),S("S2","Get on the step and lift off at minimum speed"),S("S3","Establish positive climb and retract flaps")],
["ASES","AMES"]),
T("L","IV_M","Rough Water Approach and Landing","CA.IV.M",
"Demonstrate a rough water landing with commercial precision. Explain how technique differs from normal water landing.",
[K("K1","Rough water landing technique"),K("K2","Touchdown attitude to minimize wave impact"),K("K3","Use of power during rough water landing")],
[R("R1","Structural damage from hard water landing"),R("R2","Capsizing from improper water handling")],
[S("S1","Approach at proper airspeed with appropriate flaps"),S("S2","Touch down at minimum speed in proper attitude"),S("S3","Use power to control descent rate near the surface")],
["ASES","AMES"]),
T("M","IV_N","Confined Area Takeoff and Climb","CA.IV.N",
"You need to depart from a small, confined cove. Demonstrate confined area water takeoff.",
[K("K1","Confined area water operations"),K("K2","Step taxi techniques in confined areas"),K("K3","Wind and current assessment for confined water areas")],
[R("R1","Insufficient room for takeoff run"),R("R2","Obstacles surrounding confined water area")],
[S("S1","Assess wind, current, and obstructions"),S("S2","Plan and execute departure path for maximum distance"),S("S3","Lift off and clear obstacles at Vx")],
["ASES","AMES"]),
T("N","IV_O","Confined Area Approach and Landing","CA.IV.O",
"Demonstrate an approach and landing into a confined water area, accounting for obstacles and water conditions.",
[K("K1","Confined area water landing technique"),K("K2","Approach planning for obstacles and available water area"),K("K3","Go-around decision criteria for confined water areas")],
[R("R1","Landing in area too small to take off from"),R("R2","Striking obstacles on approach")],
[S("S1","Evaluate water area for suitability and hazards"),S("S2","Execute approach clearing all obstacles"),S("S3","Land and stop within available water area")],
["ASES","AMES"])
]},
{ id:"V", roman:"V", title:"Performance and Ground Reference Maneuvers", phase:"flight", tasks:[
T("A","V_A","Steep Turns","CA.V.A",
"Demonstrate steep turns at 50 degrees  bank in both directions. Commercial standards: altitude \u00b1100 ft, airspeed \u00b110 kt.",
[K("K1","Aerodynamics of steep turns at 50 degrees  bank"),K("K2","Load factor and maneuvering speed considerations")],
[R("R1","Exceeding structural limits at steep bank angles"),R("R2","Inadvertent stall or spiral at 50 degrees  bank")],
[S("S1","Maintain 50 degrees  bank \u00b15 degrees "),S("S2","Maintain altitude \u00b1100 ft, airspeed \u00b110 kt"),S("S3","Roll out on entry heading \u00b110 degrees ")]),
T("B","V_B","Steep Spiral","CA.V.B",
"Demonstrate a steep spiral descent around a ground reference point through at least three 360 degrees  turns.",
[K("K1","Steep spiral technique and ground reference"),K("K2","Wind correction during spiral descent"),K("K3","Speed and bank management")],
[R("R1","Excessive speed in spiral descent"),R("R2","Loss of ground reference point")],
[S("S1","Establish and maintain steep spiral around point"),S("S2","Apply wind correction for constant radius"),S("S3","Maintain airspeed within limits throughout")],
["ASEL","ASES"]),
T("C","V_C","Chandelles","CA.V.C",
"Demonstrate chandelles in both directions. I'm evaluating your coordination, timing, and energy management.",
[K("K1","Chandelle technique (climbing 180 degrees  turn)"),K("K2","Coordination of bank and pitch throughout maneuver"),K("K3","Relationship between bank angle and pitch for maximum altitude gain")],
[R("R1","Stall from improper speed management"),R("R2","Uncoordinated flight during maneuver")],
[S("S1","Establish proper entry speed and bank"),S("S2","Complete 180 degrees  turn with max altitude gain"),S("S3","Roll out on heading at minimum controllable airspeed")]),
T("D","V_D","Lazy Eights","CA.V.D",
"Demonstrate lazy eights. I'm looking for symmetry, coordination, and smooth transitions.",
[K("K1","Lazy eight technique and objectives"),K("K2","Symmetry and coordination requirements"),K("K3","Speed, altitude, and bank relationships throughout")],
[R("R1","Uncoordinated flight during transitions"),R("R2","Asymmetric maneuver execution")],
[S("S1","Perform symmetrical lazy eights"),S("S2","Maintain coordination throughout"),S("S3","Achieve proper altitude, airspeed, bank at each reference point")]),
T("E","V_E","Eights on Pylons","CA.V.E",
"Demonstrate eights on pylons, maintaining the line of sight on each pylon while adjusting for wind.",
[K("K1","Eights on pylons technique and pivotal altitude"),K("K2","Pivotal altitude calculation and adjustment"),K("K3","Wind effects on pylon tracking")],
[R("R1","Flying at incorrect pivotal altitude"),R("R2","Fixation on pylon to exclusion of traffic scan")],
[S("S1","Select appropriate pylons and determine pivotal altitude"),S("S2","Maintain line of sight on pylon through altitude adjustments"),S("S3","Correct for wind and maintain ground track")])
]},
{ id:"VI", roman:"VI", title:"Navigation", phase:"flight", tasks:[
T("A","VI_A","Pilotage and Dead Reckoning","CA.VI.A",
"Navigate the cross-country route using pilotage and dead reckoning at the commercial standard.",
[K("K1","Advanced pilotage and dead reckoning"),K("K2","Time, speed, distance calculations in flight")],
[R("R1","Becoming disoriented during commercial operations"),R("R2","Deviation from planned route")],
[S("S1","Navigate accurately using pilotage and DR"),S("S2","Maintain heading \u00b110 degrees , altitude \u00b1200 ft")]),
T("B","VI_B","Navigation Systems and Radar Services","CA.VI.B",
"Demonstrate proficient use of all installed navigation systems and ATC radar services.",
[K("K1","Advanced navigation system use"),K("K2","ATC services for commercial operations")],
[R("R1","Navigation system failure during commercial flight"),R("R2","Inefficient use of ATC resources")],
[S("S1","Proficiently use all installed navigation systems"),S("S2","Effectively utilize ATC radar services")])
]},
{ id:"VII", roman:"VII", title:"Slow Flight and Stalls", phase:"flight", tasks:[
T("A","VII_A","Maneuvering During Slow Flight","CA.VII.A",
"Demonstrate slow flight in a complex aircraft at commercial-level proficiency.",
[K("K1","Slow flight in complex aircraft configurations"),K("K2","Effects of complex systems on slow flight characteristics")],
[R("R1","Stall in complex configuration"),R("R2","Gear/flap management at slow speed")],
[S("S1","Establish and maintain slow flight"),S("S2","Perform turns, climbs, descents at slow speed"),S("S3","Maintain altitude \u00b150 ft, heading \u00b110 degrees ")]),
T("B","VII_B","Power-Off Stalls","CA.VII.B",
"Demonstrate power-off stall recognition and recovery in a complex aircraft.",
[K("K1","Power-off stall characteristics in complex aircraft"),K("K2","Recovery procedure with complex systems")],
[R("R1","Delayed recovery in complex configuration"),R("R2","Inadvertent gear extension during recovery")],
[S("S1","Recognize stall onset and recover promptly"),S("S2","Recover with minimal altitude loss"),S("S3","Manage complex systems during recovery")]),
T("C","VII_C","Power-On Stalls","CA.VII.C",
"Demonstrate power-on stall recognition and recovery.",
[K("K1","Power-on stall characteristics"),K("K2","Left-turning tendencies during power-on stall")],
[R("R1","Spin entry from uncoordinated power-on stall"),R("R2","Excessive altitude loss during recovery")],
[S("S1","Induce stall from takeoff configuration"),S("S2","Recover promptly with minimal altitude loss")]),
T("D","VII_D","Accelerated Stalls","CA.VII.D",
"Demonstrate recognition and recovery from an accelerated stall during a steep turn.",
[K("K1","Accelerated stall aerodynamics"),K("K2","Load factor effects on stall speed"),K("K3","Recovery from accelerated stall")],
[R("R1","Exceeding G-limits during accelerated stall"),R("R2","Structural damage from abrupt maneuvering")],
[S("S1","Recognize accelerated stall onset"),S("S2","Recover by reducing load factor and AOA")]),
T("E","VII_E","Spin Awareness","CA.VII.E",
"Explain spin entry, phases, and recovery procedures applicable to this aircraft.",
[K("K1","Spin aerodynamics and recovery"),K("K2","Aircraft-specific spin characteristics"),K("K3","Weight and CG effects on spin behavior")],
[R("R1","Uncoordinated flight near stall speed"),R("R2","Cross-controlled conditions")],
[S("S1","Explain spin awareness and avoidance"),S("S2","Describe PARE recovery procedure")])
]},
{ id:"VIII", roman:"VIII", title:"High-Altitude Operations", phase:"flight", tasks:[
T("A","VIII_A","Supplemental Oxygen","CA.VIII.A",
"Explain supplemental oxygen requirements and procedures for flight above 12,500 feet.",
[K("K1","Supplemental oxygen regulatory requirements (14 CFR 91.211)"),K("K2","Types of oxygen systems and their capabilities"),K("K3","Hypoxia symptoms and time of useful consciousness")],
[R("R1","Hypoxia onset without supplemental oxygen"),R("R2","Equipment malfunction at altitude")],
[S("S1","Determine oxygen requirements for planned flight"),S("S2","Operate supplemental oxygen system")]),
T("B","VIII_B","Pressurization","CA.VIII.B",
"Describe pressurization system operation, limitations, and emergency procedures for rapid decompression.",
[K("K1","Pressurization system operation and controls"),K("K2","Cabin altitude and differential pressure limits"),K("K3","Rapid decompression procedures")],
[R("R1","Pressurization system failure at altitude"),R("R2","Exceeding cabin altitude limits")],
[S("S1","Describe pressurization system operation"),S("S2","Explain emergency descent procedures")])
]},
{ id:"IX", roman:"IX", title:"Emergency Operations", phase:"flight", tasks:[
T("A","IX_A","Emergency Descent","CA.IX.A",
"Demonstrate an emergency descent as if responding to cabin fire or decompression.",
[K("K1","Emergency descent procedures"),K("K2","Configuration for maximum descent rate"),K("K3","Structural and speed limitations during descent")],
[R("R1","Exceeding Vne during emergency descent"),R("R2","Delayed initiation of emergency descent")],
[S("S1","Establish emergency descent configuration"),S("S2","Achieve maximum rate descent within limits"),S("S3","Level off at appropriate altitude")]),
T("B","IX_B","Emergency Approach and Landing","CA.IX.B",
"Engine failure en route. Demonstrate emergency approach and landing procedures.",
[K("K1","Engine failure procedures and best glide"),K("K2","Emergency landing site selection"),K("K3","Emergency communications and squawk procedures")],
[R("R1","Poor field selection"),R("R2","Failure to maintain best glide speed")],
[S("S1","Establish best glide immediately"),S("S2","Select and plan approach to suitable field"),S("S3","Complete emergency checklist")],
["ASEL","ASES"]),
T("C","IX_C","Systems and Equipment Malfunctions","CA.IX.C",
"Describe response procedures for various system malfunctions in a complex aircraft.",
[K("K1","System malfunction procedures per POH"),K("K2","Partial panel operations"),K("K3","Complex aircraft emergency procedures")],
[R("R1","Misidentification of failed system"),R("R2","Continued flight with critical malfunction")],
[S("S1","Identify malfunction and apply correct procedure"),S("S2","Make appropriate landing/diversion decision")]),
T("D","IX_D","Emergency Equipment and Survival Gear","CA.IX.D",
"Identify all emergency equipment and describe survival procedures for commercial operations.",
[K("K1","Emergency equipment location and use"),K("K2","ELT operation"),K("K3","Survival gear for commercial flight environments")],
[R("R1","Unfamiliarity with emergency equipment"),R("R2","Inadequate survival preparations")],
[S("S1","Locate and demonstrate emergency equipment use"),S("S2","Describe survival priorities and procedures")]),
T("E","IX_E","Engine Failure During Takeoff Before VMC","CA.IX.E",
"Describe and demonstrate the procedure for engine failure during takeoff before reaching VMC.",
[K("K1","VMC and engine failure recognition"),K("K2","Procedures for engine failure before VMC")],
[R("R1","Loss of directional control below VMC"),R("R2","Delayed recognition of engine failure")],
[S("S1","Recognize engine failure promptly"),S("S2","Maintain directional control and abort takeoff")],
["AMEL","AMES"]),
T("F","IX_F","Engine Failure After Liftoff","CA.IX.F",
"Demonstrate procedures for engine failure after liftoff in a multiengine aircraft.",
[K("K1","Critical engine failure after liftoff procedures"),K("K2","Identify, verify, feather sequence"),K("K3","Single-engine climb performance")],
[R("R1","Loss of control from asymmetric thrust"),R("R2","Failure to identify correct engine")],
[S("S1","Maintain aircraft control (pitch, bank, rudder)"),S("S2","Identify, verify, and feather failed engine"),S("S3","Establish single-engine climb or controlled descent")],
["AMEL","AMES"]),
T("G","IX_G","Approach and Landing with Inoperative Engine","CA.IX.G",
"Demonstrate an approach and landing with a simulated inoperative engine.",
[K("K1","Single-engine approach procedures"),K("K2","Configuration management for single-engine approach"),K("K3","Go-around considerations on one engine")],
[R("R1","VMC roll during single-engine approach"),R("R2","Gear/flap configuration errors on one engine")],
[S("S1","Fly a stabilized single-engine approach"),S("S2","Manage configuration for single-engine landing"),S("S3","Execute safe landing with inoperative engine")],
["AMEL","AMES"])
]},
{ id:"X", roman:"X", title:"Multiengine Operations", phase:"flight", tasks:[
T("A","X_A","Maneuvering with One Engine Inoperative","CA.X.A",
"Demonstrate maneuvering flight with one engine inoperative including turns, climbs, and descents.",
[K("K1","Single-engine aerodynamics, including VMC, critical engine, zero sideslip, and performance factors"),K("K2","Control technique for one-engine-inoperative operations"),K("K3","Performance limitations with one engine inoperative")],
[R("R1","Loss of directional control with one engine inoperative"),R("R2","Stall or loss of control below VMC"),R("R3","Improper configuration or excessive drag with one engine inoperative")],
[S("S1","Maintain positive aircraft control with one engine inoperative"),S("S2","Demonstrate turns, climbs, and descents with one engine inoperative"),S("S3","Maintain altitude ±100 ft and heading ±10 degrees")],
["AMEL","AMES"]),
T("B","X_B","VMC Demonstration","CA.X.B",
"Demonstrate VMC. Explain the factors that affect VMC and recovery procedures.",
[K("K1","VMC definition and factors including weight, CG, altitude, configuration, bank, and critical engine"),K("K2","Recognition of VMC and proper recovery procedure"),K("K3","Relationship between VMC and stall speed")],
[R("R1","Loss of directional control during VMC demonstration"),R("R2","Stall before reaching VMC"),R("R3","Improper recovery technique")],
[S("S1","Set up and demonstrate VMC"),S("S2","Recover at the first indication of loss of directional control, stall warning, or buffet"),S("S3","Explain factors affecting VMC")],
["AMEL","AMES"]),
T("C","X_C","Engine Failure During Flight (Simulated) solely by Reference to Instruments","CA.X.C",
"Demonstrate control, navigation, and aircraft management after a simulated engine failure during flight solely by reference to instruments.",
[K("K1","Procedures for simulated engine failure during flight solely by reference to instruments"),K("K2","Aircraft control, configuration, and performance considerations with one engine inoperative under instrument conditions"),K("K3","Checklist use and engine securing procedures as appropriate")],
[R("R1","Loss of control while operating solely by reference to instruments"),R("R2","Failure to maintain directional control or appropriate airspeed"),R("R3","Improper checklist use or task saturation")],
[S("S1","Maintain aircraft control solely by reference to instruments with one engine inoperative"),S("S2","Establish appropriate configuration and airspeed"),S("S3","Use appropriate checklist and maintain altitude, heading, and airspeed within ACS standards")],
["AMEL","AMES"]),
T("D","X_D","Instrument Approach and Landing with an Inoperative Engine (Simulated)","CA.X.D",
"Fly an instrument approach and landing with one engine inoperative.",
[K("K1","One-engine-inoperative instrument approach procedures"),K("K2","Configuration and speed management during a one-engine-inoperative approach"),K("K3","Missed approach considerations with one engine inoperative")],
[R("R1","Loss of directional control during the one-engine-inoperative approach"),R("R2","Configuration or airspeed errors during the instrument approach"),R("R3","Unstable approach or improper missed approach decision-making")],
[S("S1","Fly a stabilized one-engine-inoperative instrument approach"),S("S2","Manage configuration, speed, and checklist use throughout the approach"),S("S3","Land or execute the missed approach procedure as required")],
["AMEL","AMES"])
]},
{ id:"XI", roman:"XI", title:"Postflight Procedures", phase:"flight", tasks:[
T("A","XI_A","After Landing, Parking, and Securing","CA.XI.A",
"Complete postflight procedures for a complex aircraft including all required inspections and documentation.",
[K("K1","Complex aircraft shutdown procedures"),K("K2","Post-flight inspection requirements"),K("K3","Discrepancy recording for commercial aircraft")],
[R("R1","Improper shutdown of complex systems"),R("R2","Failure to document discrepancies")],
[S("S1","Complete shutdown and securing checklist"),S("S2","Perform post-flight inspection"),S("S3","Document any discrepancies")])
]}
];
